"""
clawlippytm.creativity
~~~~~~~~~~~~~~~~~~~~~~~

Enhanced creativity engine for Clawlippytm.Bots.

The :class:`CreativityEngine` enriches candidate responses generated by the
:class:`~clawlippytm.cognitive_reasoning.CognitiveReasoner` with:

- Analogical elaboration (relating concepts to vivid analogies).
- Narrative framing (wrapping dry analysis in a light narrative arc).
- Lexical diversification (vocabulary variation based on temperature).
- Metaphor injection (adding colour at high temperature settings).
"""

from __future__ import annotations

import random
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class CreativityAnnotation:
    """Tracks what creative transforms were applied to a response."""

    analogies_added: int = 0
    narrative_framing: bool = False
    metaphors_added: int = 0
    lexical_substitutions: int = 0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "analogies_added": self.analogies_added,
            "narrative_framing": self.narrative_framing,
            "metaphors_added": self.metaphors_added,
            "lexical_substitutions": self.lexical_substitutions,
        }


# ---------------------------------------------------------------------------
# Creativity engine
# ---------------------------------------------------------------------------

class CreativityEngine:
    """
    Response enrichment engine driven by a *temperature* parameter.

    At low temperatures (≤ 0.3) the engine applies minimal transforms;
    at high temperatures (≥ 0.8) it injects richer narrative and metaphor.

    Parameters
    ----------
    temperature:
        Float in [0.0, 1.0].  Controls the degree of creative enrichment.
    seed:
        Optional random seed for reproducible output.
    """

    # --- Analogies library ---
    _ANALOGIES: List[str] = [
        "like a compass guiding a ship through fog",
        "much like a skilled craftsman shaping raw material into art",
        "similar to how a river carves its path through stone over time",
        "akin to tuning an instrument before a performance",
        "reminiscent of how roots anchor a tree while branches reach skyward",
        "comparable to assembling a mosaic where each piece reveals the whole",
        "not unlike a conductor unifying individual musicians into harmony",
        "as illuminating as a lighthouse beam cutting through the dark",
    ]

    # --- Metaphor phrases ---
    _METAPHORS: List[str] = [
        "a tapestry of interconnected ideas",
        "the architecture of thought itself",
        "a bridge between the known and the unexplored",
        "the spark that ignites deeper understanding",
        "the lens through which clarity emerges",
        "a symphony of concepts working in concert",
        "the scaffolding upon which insight is built",
    ]

    # --- Lexical substitution pairs (original → enriched) ---
    _LEXICAL_PAIRS: Dict[str, str] = {
        "important": "pivotal",
        "good": "exceptional",
        "bad": "detrimental",
        "use": "leverage",
        "make": "craft",
        "show": "illuminate",
        "help": "empower",
        "change": "transform",
        "start": "initiate",
        "end": "culminate",
        "think": "contemplate",
        "see": "perceive",
        "get": "acquire",
        "give": "bestow",
        "need": "require",
    }

    def __init__(
        self,
        temperature: float = 0.7,
        seed: Optional[int] = None,
    ) -> None:
        self.temperature: float = max(0.0, min(temperature, 1.0))
        self._rng: random.Random = random.Random(seed)
        self._enrichment_count: int = 0
        self._last_annotation: Optional[CreativityAnnotation] = None

    # ------------------------------------------------------------------
    # Public methods
    # ------------------------------------------------------------------

    def enrich(
        self,
        base_response: str,
        reasoning_trace: Optional[Any] = None,
    ) -> str:
        """
        Apply creative enrichment to *base_response*.

        Parameters
        ----------
        base_response:
            The raw candidate response from the cognitive reasoner.
        reasoning_trace:
            Optional trace (list of :class:`ReasoningStep`) used to infer
            topic keywords for analogy selection.

        Returns
        -------
        str
            Enriched response string.
        """
        annotation = CreativityAnnotation()
        result = base_response

        # --- Lexical diversification (applied at all temperatures) ---
        result, subs = self._diversify_lexicon(result)
        annotation.lexical_substitutions = subs

        # --- Analogy injection (temperature ≥ 0.4) ---
        if self.temperature >= 0.4:
            result, n_analogies = self._inject_analogies(result)
            annotation.analogies_added = n_analogies

        # --- Metaphor injection (temperature ≥ 0.65) ---
        if self.temperature >= 0.65:
            result, n_metaphors = self._inject_metaphors(result)
            annotation.metaphors_added = n_metaphors

        # --- Narrative framing (temperature ≥ 0.8) ---
        if self.temperature >= 0.8:
            result = self._apply_narrative_framing(result)
            annotation.narrative_framing = True

        self._enrichment_count += 1
        self._last_annotation = annotation
        return result

    def summary(self) -> Dict[str, Any]:
        """Return a summary of creativity engine activity."""
        return {
            "temperature": self.temperature,
            "enrichments_applied": self._enrichment_count,
            "last_annotation": (
                self._last_annotation.to_dict()
                if self._last_annotation
                else None
            ),
        }

    # ------------------------------------------------------------------
    # Internal transforms
    # ------------------------------------------------------------------

    def _diversify_lexicon(self, text: str) -> tuple[str, int]:
        """
        Replace common words with more expressive alternatives.

        The substitution probability scales with temperature so that at
        low temperatures fewer words are replaced.
        """
        substitutions = 0
        words = text.split()
        result_words: List[str] = []
        for word in words:
            clean = re.sub(r"[^\w]", "", word.lower())
            if (
                clean in self._LEXICAL_PAIRS
                and self._rng.random() < self.temperature * 0.6
            ):
                replacement = self._LEXICAL_PAIRS[clean]
                # Preserve surrounding punctuation
                new_word = re.sub(r"\w+", replacement, word, count=1)
                result_words.append(new_word)
                substitutions += 1
            else:
                result_words.append(word)
        return " ".join(result_words), substitutions

    def _inject_analogies(self, text: str) -> tuple[str, int]:
        """
        Append an analogy phrase to the response.

        The number of analogies added (0–2) scales with temperature.
        """
        max_analogies = int(self.temperature * 2)
        n = self._rng.randint(0, max(0, max_analogies))
        if n == 0:
            return text, 0
        analogies = self._rng.sample(self._ANALOGIES, min(n, len(self._ANALOGIES)))
        suffix = "  " + ";  ".join(analogies) + "."
        return text + suffix, len(analogies)

    def _inject_metaphors(self, text: str) -> tuple[str, int]:
        """
        Embed a metaphor into the response as a parenthetical flourish.
        """
        if self._rng.random() > self.temperature:
            return text, 0
        metaphor = self._rng.choice(self._METAPHORS)
        insertion = f" — {metaphor} —"
        # Insert after the first sentence boundary, or at the end
        match = re.search(r"[.!?]\s+", text)
        if match:
            pos = match.end()
            text = text[:pos] + insertion + " " + text[pos:]
        else:
            text = text + insertion
        return text, 1

    def _apply_narrative_framing(self, text: str) -> str:
        """
        Wrap the response in a light narrative arc (opening hook + closing).
        """
        hooks = [
            "Imagine standing at the edge of understanding — ",
            "Picture a world where every concept unfolds like a story: ",
            "Consider, for a moment, the journey of an idea: ",
            "Let's embark on a thoughtful exploration: ",
        ]
        closings = [
            " And so, the threads of this inquiry weave together into a richer tapestry of knowledge.",
            " Together, these insights form a living mosaic that continues to evolve.",
            " Ultimately, every question answered opens a new horizon of discovery.",
            " In this light, understanding becomes not a destination but a continuous, wondrous journey.",
        ]
        hook = self._rng.choice(hooks)
        closing = self._rng.choice(closings)
        return hook + text + closing
